source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'rest-client'
gem 'game_of_thrones_api'
gem 'tty-prompt'
gem 'colorize'
gem 'tty-color'
gem 'tty-box'
gem 'rmagick'
gem 'catpix', '~> 0.2.0'